# .github/workflows/ci.yml
name: CI - Build and Test

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⚙️ Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: 🐳 Build Docker Images
        run: |
          docker build -t client ./client
          docker build -t server ./server
          docker build -t proxy ./proxy

      - name: ✅ Run Backend Tests (if exists)
        run: |
          if [ -f "./server/pyproject.toml" ]; then
            docker run --rm server pytest
          else
            echo "No backend tests found"
          fi

      - name: ✅ Run Frontend Tests (if exists)
        run: |
          if [ -f "./client/package.json" ]; then
            cd client && npm install && npm test || true
          else
            echo "No frontend tests found"
          fi
